stages:
  - build
  - deploy

build-package:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 7 days
    paths:
      - ./build/

release-package:
  stage: deploy
  image: node:latest
  script:
    - echo $NPM_AUTH_TOKEN
    - echo ${NPM_AUTH_TOKEN}
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - npm version $CI_COMMIT_TAG
    - npm publish
  only:
    - tags
